### ISSUE TITLE
メールの設定をいじるように喚起

### ISSUE THREAD

**Issue by HajimeONO** [TsukubaShogi/Tsukusho#2]
申し込みのあたりに書く

**Comment by yukirinn07** [comment]
メールの設定をいじるようにとは？

> 入力したメアド先に確認メールが送られますのでxxxxxxxx@xxx.xxからのメールを受け取れるようにしておいて下さい。

とかではなく？

**Comment by HajimeONO** [comment]
それをHP自体にも書いておきたい

**Comment by yukirinn07** [comment]
あっ、そーゆーことね
了解
